### ISSUE TITLE
Pre-realase todo

### ISSUE THREAD

**Issue by fvella** [fvella/MGBC#3]
- [ ] Add MPI-IO support
- [ ] Add OpenMP R-MATH generator for single GPU configuration
- [ ] Remove deprecated MPI functions
- [ ] Change source file name and clean-up the code
